# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Cross-platform Gradle Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-macos:
    name: Build macOS (.dmg)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .dmg
        run: ./gradlew packageDmg

      - name: Upload .dmg to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/compose/binaries/main/dmg/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-windows:
    name: Build Windows (.msi, .exe)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .msi and .exe
        run: .\gradlew.bat packageMsi packageExe

      - name: Upload .msi and .exe to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/compose/binaries/main/msi/*.msi
            build/compose/binaries/main/exe/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-linux:
    name: Build Linux (.deb)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build .deb
        run: ./gradlew packageDeb

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/compose/binaries/main/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}